# Generated by Django 5.1.4 on 2024-12-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='cin',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
