# Generated by Django 5.1.4 on 2024-12-07 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_offer_order_offer_order_orderimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='order_images/'),
        ),
        migrations.CreateModel(
            name='OrderMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='order_media/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='service.order')),
            ],
        ),
    ]
