# Generated by Django 5.1.4 on 2024-12-07 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_order_images_ordermedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='images',
        ),
        migrations.DeleteModel(
            name='OrderImage',
        ),
    ]
