# Generated by Django 5.1.4 on 2024-12-07 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
        ('service', '0004_remove_order_images_delete_orderimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Confirmed_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='provider.provider'),
        ),
    ]
