# Generated by Django 5.1.4 on 2024-12-09 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_remove_order_state_offer_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='proposed_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
